on: [push, pull_request]
name: Build wrtcrd
jobs:
  build-wrtcrd:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libxtst-dev
      - if: matrix.os == 'windows-latest'
        run: echo "Windows"
      - if: matrix.os == 'macos-latest'
        run: echo "macOS"
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: |
          go build -tags "h264enc" cmd/main.go
          ls -alh
          ls -alh cmd/
