on:
  push:
    branches:
      - main
  release:
    types: [ created ]
name: Build wrtcrd
jobs:
  build-wrtcrd:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Linux"
          sudo apt-get install -y libxtst-dev
          go build -tags "h264enc" cmd/main.go
          mv main wrtcrd
          ls -alh
      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "macOS"
          go build -tags "h264enc" cmd/main.go
          mv main wrtcrd
          ls -alh
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "Windows"
          go build -tags "h264enc" cmd/main.go
          mv main.exe wrtcrd.exe
      - name: Upload Linux artifacts
        if: github.event_name == 'release' && matrix.os == 'ubuntu-latest'
        run: |
          set -x
          FILE=wrtcrd
          ASSET=wrtcrd-x64-linux
          # Token should have permission repo -> public_repo (https://stackoverflow.com/a/37632339)
          curl -H "Authorization: token ${{ secrets.WRTCRD_TOKEN }}" -H "Content-Type: $(file -b --mime-type $FILE)" --data-binary @$FILE \
              "https://uploads.github.com/repos/kafeg/wrtcrd/releases/${{ github.event.release.id }}/assets?name=$(basename $ASSET)"
      - name: Upload macOS artifacts
        if: github.event_name == 'release' && matrix.os == 'macos-latest'
        run: |
          set -x
          FILE=wrtcrd
          ASSET=wrtcrd-x64-osx
          curl -H "Authorization: token ${{ secrets.WRTCRD_TOKEN }}" -H "Content-Type: $(file -b --mime-type $FILE)" --data-binary @$FILE \
              "https://uploads.github.com/repos/kafeg/wrtcrd/releases/${{ github.event.release.id }}/assets?name=$(basename $ASSET)"
      - name: Upload Windows artifacts
        shell: bash
        if: github.event_name == 'release' && matrix.os == 'windows-latest'
        run: |
          FILE=wrtcrd.exe
          ASSET=wrtcrd-x64-osx.exe
          curl -H "Authorization: token ${{ secrets.WRTCRD_TOKEN }}" -H "Content-Type: $(file -b --mime-type $FILE)" --data-binary @$FILE \
              "https://uploads.github.com/repos/kafeg/wrtcrd/releases/${{ github.event.release.id }}/assets?name=$(basename $ASSET)"
