on:
  push:
    branches:
      - main
  release:
    types: [ created ]
name: Build wrtcrd
jobs:
  build-wrtcrd:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Linux"
          sudo apt-get install -y libxtst-dev
          go build -tags "h264enc" cmd/main.go
          mv main wrtcrd
          ls -alh
      - if: matrix.os == 'macos-latest'
        run: |
          echo "macOS"
          go build -tags "h264enc" cmd/main.go
          mv main wrtcrd
          ls -alh
      - if: matrix.os == 'windows-latest'
        run: |
          echo "Windows"
          go build -tags "h264enc" cmd/main.go
          mv main.exe wrtcrd.exe
      - if: github.event_name != 'push' && matrix.os == 'ubuntu-latest'
        run: |
          set -x
          FILE=wrtcrd
          ASSET=wrtcrd-x64-linux
          curl -H "Authorization: token ${{ secrets.WRTCRD_TOKEN }}" -H "Content-Type: $(file -b --mime-type $FILE)" --data-binary @$FILE \
              "https://uploads.github.com/repos/kafeg/wrtcrd/releases/${{ github.event.release.id }}/assets?name=$(basename $ASSET)"
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.WRTCRD_TOKEN }}
#          file: wrtcrd
#          asset_name: wrtcrd-x64-linux
#          tag: ${{ github.ref }}
#      - if: github.event_name != 'push' && matrix.os == 'macos-latest'
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.WRTCRD_TOKEN }}
#          file: wrtcrd
#          asset_name: wrtcrd-x64-osx
#          tag: ${{ github.ref }}
#      - if: github.event_name != 'push' && matrix.os == 'windows-latest'
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.WRTCRD_TOKEN }}
#          file: wrtcrd.exe
#          asset_name: wrtcrd-x64-windows.exe
#          tag: ${{ github.ref }}
